In [2]:
import fastf1 as ff1
import pandas as pd
from fastf1.ergast import Ergast
import numpy as np

In [3]:
#Crear el dataframe
df = pd.DataFrame()

In [3]:
ergast = Ergast()
#Cargar la sesión de la carrera
Bahrain_R = ff1.get_session(2023, 14, 'R')

Bahrain_R.load(weather = True)

laps = Bahrain_R.laps

req         WARNING

DEFAULT CACHE ENABLED!
	Cache directory: C:\Users\user\AppData\Local\Temp\fastf1.
	Size: 2.22 GB
core           INFO 	Loading data for Italian Grand Prix - Race [v3.0.7]
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '55', '16', '63', '44', '23', '4', '14', '77', '40', '81', '2', '24', '10', '18', '27', '20', '31', '22']

In [18]:
carrera = ergast.get_circuits(season=2023, round=14)
carrera
nombre = str(carrera['circuitName'])


result = nombre.rsplit('\n', 3)[0]
resultant_string = result[5:]
print(resultant_string)

Autodromo Nazionale di Monza

In [7]:
nombre = str(carrera['circuitId'])
nombre

'0    monza\nName: circuitId, dtype: object'

In [23]:
res = Bahrain_R.results

res.head(5)

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,CountryCode,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points
1,1,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,3671C6,red_bull,Max,Verstappen,Max Verstappen,...,NED,1.0,1,2.0,NaT,NaT,NaT,0 days 01:13:41.143000,Finished,25.0
11,11,S PEREZ,PER,perez,Red Bull Racing,3671C6,red_bull,Sergio,Perez,Sergio Perez,...,MEX,2.0,2,5.0,NaT,NaT,NaT,0 days 00:00:06.064000,Finished,18.0
55,55,C SAINZ,SAI,sainz,Ferrari,F91536,ferrari,Carlos,Sainz,Carlos Sainz,...,ESP,3.0,3,1.0,NaT,NaT,NaT,0 days 00:00:11.193000,Finished,15.0
16,16,C LECLERC,LEC,leclerc,Ferrari,F91536,ferrari,Charles,Leclerc,Charles Leclerc,...,MON,4.0,4,3.0,NaT,NaT,NaT,0 days 00:00:11.377000,Finished,12.0
63,63,G RUSSELL,RUS,russell,Mercedes,6CD3BF,mercedes,George,Russell,George Russell,...,GBR,5.0,5,4.0,NaT,NaT,NaT,0 days 00:00:23.028000,Finished,10.0

In [24]:
#Asignar nombre, abreviación, equipo, e información del circuito
df['driver_name'] = res.BroadcastName
df['driver_abb'] = res.Abbreviation
df['team_name'] = res.TeamName
df['circuit_name'] = 'Bahrain International Circuit'
df['circuit_country'] = 'Bahrain'
df.head(5)

,driver_name,driver_abb,team_name,circuit_name,circuit_country
1,M VERSTAPPEN,VER,Red Bull Racing,Bahrain International Circuit,Bahrain
11,S PEREZ,PER,Red Bull Racing,Bahrain International Circuit,Bahrain
55,C SAINZ,SAI,Ferrari,Bahrain International Circuit,Bahrain
16,C LECLERC,LEC,Ferrari,Bahrain International Circuit,Bahrain
63,G RUSSELL,RUS,Mercedes,Bahrain International Circuit,Bahrain

In [28]:
df2 = pd.DataFrame()

df2['circuit_name'] = carrera['circuitName']
df2['circuit_country'] = carrera['country']
df2

                    circuit_name circuit_country
0  Bahrain International Circuit         Bahrain

In [6]:
#Vuelta más rápida de la carrera
ver_lap = laps.pick_driver('VER')
mini = ver_lap['LapTime'].min()
mini

Timedelta('0 days 00:01:36.236000')

In [7]:
#Clasificación actual de constructores
const_stand = ergast.get_constructor_standings(season=2023)
const_stand.content[0]

,position,positionText,points,wins,constructorId,constructorUrl,constructorName,constructorNationality
0,1,1,583.0,14,red_bull,http://en.wikipedia.org/wiki/Red_Bull_Racing,Red Bull,Austrian
1,2,2,273.0,0,mercedes,http://en.wikipedia.org/wiki/Mercedes-Benz_in_...,Mercedes,German
2,3,3,228.0,0,ferrari,http://en.wikipedia.org/wiki/Scuderia_Ferrari,Ferrari,Italian
3,4,4,217.0,0,aston_martin,http://en.wikipedia.org/wiki/Aston_Martin_in_F...,Aston Martin,British
4,5,5,115.0,0,mclaren,http://en.wikipedia.org/wiki/McLaren,McLaren,British
5,6,6,73.0,0,alpine,http://en.wikipedia.org/wiki/Alpine_F1_Team,Alpine F1 Team,French
6,7,7,21.0,0,williams,http://en.wikipedia.org/wiki/Williams_Grand_Pr...,Williams,British
7,8,8,11.0,0,haas,http://en.wikipedia.org/wiki/Haas_F1_Team,Haas F1 Team,American
8,9,9,10.0,0,alfa,http://en.wikipedia.org/wiki/Alfa_Romeo_in_For...,Alfa Romeo,Swiss
9,10,10,3.0,0,alphatauri,http://en.wikipedia.org/wiki/Scuderia_AlphaTauri,AlphaTauri,Italian

In [8]:
#Obtener informaciónd el clima en la carrera
clima = Bahrain_R.weather_data

temp = clima['AirTemp'].mean()
humi = clima['Humidity'].mean()
rain = clima['Rainfall'].mean()

print(f'La temperatura promedio es {temp}')
print(f'La humedad promedio es {humi}')
print(f'La lluvia en la {rain}')

La temperatura promedio es 27.43167701863354
La humedad promedio es 21.496894409937887
La lluvia en la 0.0

In [9]:
#Agregar la información del clima al DF
df['circuit_temp'] = temp
df['circuit_humi'] = humi
df['circuit_rain'] = rain
df.head(5)

,driver_name,driver_abb,team_name,circuit_name,circuit_country,circuit_temp,circuit_humi,circuit_rain
1,M VERSTAPPEN,VER,Red Bull Racing,Bahrain International Circuit,Bahrain,27.431677,21.496894,0.0
11,S PEREZ,PER,Red Bull Racing,Bahrain International Circuit,Bahrain,27.431677,21.496894,0.0
14,F ALONSO,ALO,Aston Martin,Bahrain International Circuit,Bahrain,27.431677,21.496894,0.0
55,C SAINZ,SAI,Ferrari,Bahrain International Circuit,Bahrain,27.431677,21.496894,0.0
44,L HAMILTON,HAM,Mercedes,Bahrain International Circuit,Bahrain,27.431677,21.496894,0.0

In [10]:
#Cargar la carrera de clasificación
Bahrain_Q = ff1.get_session(2023, 1, 'Q')

Bahrain_Q.load()
res_Q = Bahrain_Q.results
res_Q.head(5)

core           INFO 	Loading data for Bahrain Grand Prix - Qualifying [v3.0.7]
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for timing_data
req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '16', '55', '14', '63', '44', '18', '31', '27', '4', '77', '24', '22', '23', '2', '20', '81', '21', '10']

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,CountryCode,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points
1,1,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,3671C6,red_bull,Max,Verstappen,Max Verstappen,...,NED,1.0,,NaN,0 days 00:01:31.295000,0 days 00:01:30.503000,0 days 00:01:29.708000,NaT,,NaN
11,11,S PEREZ,PER,perez,Red Bull Racing,3671C6,red_bull,Sergio,Perez,Sergio Perez,...,MEX,2.0,,NaN,0 days 00:01:31.479000,0 days 00:01:30.746000,0 days 00:01:29.846000,NaT,,NaN
16,16,C LECLERC,LEC,leclerc,Ferrari,F91536,ferrari,Charles,Leclerc,Charles Leclerc,...,MON,3.0,,NaN,0 days 00:01:31.094000,0 days 00:01:30.282000,0 days 00:01:30,NaT,,NaN
55,55,C SAINZ,SAI,sainz,Ferrari,F91536,ferrari,Carlos,Sainz,Carlos Sainz,...,ESP,4.0,,NaN,0 days 00:01:30.993000,0 days 00:01:30.515000,0 days 00:01:30.154000,NaT,,NaN
14,14,F ALONSO,ALO,alonso,Aston Martin,358C75,aston_martin,Fernando,Alonso,Fernando Alonso,...,ESP,5.0,,NaN,0 days 00:01:31.158000,0 days 00:01:30.645000,0 days 00:01:30.336000,NaT,,NaN

In [11]:
# Actualizar los valores vacios con el último tiempo registrado de la Qualis de la carrera de clasificación
q_laptime = pd.Series(res_Q['Q3'])
q_laptime = q_laptime.fillna(res_Q['Q2'])
q_laptime = q_laptime.fillna(res_Q['Q1'])

#Transformar de datetime64 a segundos
q_laptime = q_laptime.dt.total_seconds()
q_laptime

1     89.708
11    89.846
16    90.000
55    90.154
14    90.336
63    90.340
44    90.384
18    90.836
31    90.984
27    90.809
4     91.381
77    91.443
24    91.473
22    92.510
23    91.461
2     91.652
20    91.892
81    92.101
21    92.121
10    92.181
Name: Q3, dtype: float64

In [12]:
#Añadir la posición de la Clasificatoria y el tiempo de la mejor vuelta al DF.
df['quali_pos'] = res_Q['Position']
df['quali_laptime'] = q_laptime

In [13]:
#Obtener las paradas en pits
# resyk = ergast.get_pit_stops(season=2023, round=1)
# resyk.content[0]

In [14]:
#Obtener la estrategia de llantas

stints = laps[['Driver', 'Stint', 'Compound', 'LapNumber']]
stints = stints.groupby(["Driver", "Stint", "Compound"])
stints = stints.count().reset_index()
stints = stints.rename(columns={"LapNumber": "StintLength"})
rslt = stints.loc[stints['Driver'] == 'VER']

rslt

   Driver  Stint Compound  StintLength
63    VER    1.0     SOFT           14
64    VER    2.0     SOFT           22
65    VER    3.0     HARD           21

In [15]:
#Cambio de posición

race_pos_change = pd.DataFrame()
race_pos_change['Driver'] = res.Abbreviation
race_pos_change['Quali_pos'] = res.GridPosition
race_pos_change['Race_pos'] = res.Position
race_pos_change['Change'] = res.GridPosition - res.Position

race_pos_change.head(5)

   Driver  Quali_pos  Race_pos  Change
1     VER        1.0       1.0     0.0
11    PER        2.0       2.0     0.0
14    ALO        5.0       3.0     2.0
55    SAI        4.0       4.0     0.0
44    HAM        7.0       5.0     2.0

In [16]:
df['race_pos_change'] = res.GridPosition - res.Position
df['race_pos'] = res.Position
df.head(5)

,driver_name,driver_abb,team_name,circuit_name,circuit_country,circuit_temp,circuit_humi,circuit_rain,quali_pos,quali_laptime,race_pos_change,race_pos
1,M VERSTAPPEN,VER,Red Bull Racing,Bahrain International Circuit,Bahrain,27.431677,21.496894,0.0,1.0,89.708,0.0,1.0
11,S PEREZ,PER,Red Bull Racing,Bahrain International Circuit,Bahrain,27.431677,21.496894,0.0,2.0,89.846,0.0,2.0
14,F ALONSO,ALO,Aston Martin,Bahrain International Circuit,Bahrain,27.431677,21.496894,0.0,5.0,90.336,2.0,3.0
55,C SAINZ,SAI,Ferrari,Bahrain International Circuit,Bahrain,27.431677,21.496894,0.0,4.0,90.154,0.0,4.0
44,L HAMILTON,HAM,Mercedes,Bahrain International Circuit,Bahrain,27.431677,21.496894,0.0,7.0,90.384,2.0,5.0

In [17]:
race_time1 = []

race_time1 = res.Time.dt.total_seconds()

race_time1.head(11)

1     5636.736
11      11.987
14      38.637
55      48.052
44      50.977
18      54.502
63      55.873
77      72.647
10      73.753
23      89.774
22      90.870
Name: Time, dtype: float64

In [18]:
print(len(race_time1))

20

In [19]:
race_timeF = []
x = 0
race_timeF.append(race_time1[0])

for i in range(1, 20):
    x = race_time1[0] + race_time1[i]
    race_timeF.append(x)

race_timeF

[5636.736,
 5648.723,
 5675.373,
 5684.788,
 5687.713,
 5691.238,
 5692.6089999999995,
 5709.383,
 5710.489,
 5726.51,
 5727.606,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan]

In [20]:
#Añadir el tiempo de carrera
df['race_time'] = race_timeF
#Reemplazar ceros
df['race_time'] = df['race_time'].fillna(0)
df.head(5)

,driver_name,driver_abb,team_name,circuit_name,circuit_country,circuit_temp,circuit_humi,circuit_rain,quali_pos,quali_laptime,race_pos_change,race_pos,race_time
1,M VERSTAPPEN,VER,Red Bull Racing,Bahrain International Circuit,Bahrain,27.431677,21.496894,0.0,1.0,89.708,0.0,1.0,5636.736
11,S PEREZ,PER,Red Bull Racing,Bahrain International Circuit,Bahrain,27.431677,21.496894,0.0,2.0,89.846,0.0,2.0,5648.723
14,F ALONSO,ALO,Aston Martin,Bahrain International Circuit,Bahrain,27.431677,21.496894,0.0,5.0,90.336,2.0,3.0,5675.373
55,C SAINZ,SAI,Ferrari,Bahrain International Circuit,Bahrain,27.431677,21.496894,0.0,4.0,90.154,0.0,4.0,5684.788
44,L HAMILTON,HAM,Mercedes,Bahrain International Circuit,Bahrain,27.431677,21.496894,0.0,7.0,90.384,2.0,5.0,5687.713

In [22]:
df.to_csv('df_formula1_Bahrain.csv', encoding='utf-8')

In [9]:
pilotos = ergast.get_driver_standings(season=2023, round=14)
pilotos.content[0]

,position,positionText,points,wins,driverId,driverNumber,driverCode,driverUrl,givenName,familyName,dateOfBirth,driverNationality,constructorIds,constructorUrls,constructorNames,constructorNationalities
0,1,1,364.0,12,max_verstappen,33,VER,http://en.wikipedia.org/wiki/Max_Verstappen,Max,Verstappen,1997-09-30,Dutch,[red_bull],[http://en.wikipedia.org/wiki/Red_Bull_Racing],[Red Bull],[Austrian]
1,2,2,219.0,2,perez,11,PER,http://en.wikipedia.org/wiki/Sergio_P%C3%A9rez,Sergio,Pérez,1990-01-26,Mexican,[red_bull],[http://en.wikipedia.org/wiki/Red_Bull_Racing],[Red Bull],[Austrian]
2,3,3,170.0,0,alonso,14,ALO,http://en.wikipedia.org/wiki/Fernando_Alonso,Fernando,Alonso,1981-07-29,Spanish,[aston_martin],[http://en.wikipedia.org/wiki/Aston_Martin_in_...,[Aston Martin],[British]
3,4,4,164.0,0,hamilton,44,HAM,http://en.wikipedia.org/wiki/Lewis_Hamilton,Lewis,Hamilton,1985-01-07,British,[mercedes],[http://en.wikipedia.org/wiki/Mercedes-Benz_in...,[Mercedes],[German]
4,5,5,117.0,0,sainz,55,SAI,http://en.wikipedia.org/wiki/Carlos_Sainz_Jr.,Carlos,Sainz,1994-09-01,Spanish,[ferrari],[http://en.wikipedia.org/wiki/Scuderia_Ferrari],[Ferrari],[Italian]
5,6,6,111.0,0,leclerc,16,LEC,http://en.wikipedia.org/wiki/Charles_Leclerc,Charles,Leclerc,1997-10-16,Monegasque,[ferrari],[http://en.wikipedia.org/wiki/Scuderia_Ferrari],[Ferrari],[Italian]
6,7,7,109.0,0,russell,63,RUS,http://en.wikipedia.org/wiki/George_Russell_(r...,George,Russell,1998-02-15,British,[mercedes],[http://en.wikipedia.org/wiki/Mercedes-Benz_in...,[Mercedes],[German]
7,8,8,79.0,0,norris,4,NOR,http://en.wikipedia.org/wiki/Lando_Norris,Lando,Norris,1999-11-13,British,[mclaren],[http://en.wikipedia.org/wiki/McLaren],[McLaren],[British]
8,9,9,47.0,0,stroll,18,STR,http://en.wikipedia.org/wiki/Lance_Stroll,Lance,Stroll,1998-10-29,Canadian,[aston_martin],[http://en.wikipedia.org/wiki/Aston_Martin_in_...,[Aston Martin],[British]
9,10,10,37.0,0,gasly,10,GAS,http://en.wikipedia.org/wiki/Pierre_Gasly,Pierre,Gasly,1996-02-07,French,[alpine],[http://en.wikipedia.org/wiki/Alpine_F1_Team],[Alpine F1 Team],[French]
10,11,11,36.0,0,ocon,31,OCO,http://en.wikipedia.org/wiki/Esteban_Ocon,Esteban,Ocon,1996-09-17,French,[alpine],[http://en.wikipedia.org/wiki/Alpine_F1_Team],[Alpine F1 Team],[French]
11,12,12,36.0,0,piastri,81,PIA,http://en.wikipedia.org/wiki/Oscar_Piastri,Oscar,Piastri,2001-04-06,Australian,[mclaren],[http://en.wikipedia.org/wiki/McLaren],[McLaren],[British]
12,13,13,21.0,0,albon,23,ALB,http://en.wikipedia.org/wiki/Alexander_Albon,Alexander,Albon,1996-03-23,Thai,[williams],[http://en.wikipedia.org/wiki/Williams_Grand_P...,[Williams],[British]
13,14,14,9.0,0,hulkenberg,27,HUL,http://en.wikipedia.org/wiki/Nico_H%C3%BClkenberg,Nico,Hülkenberg,1987-08-19,German,[haas],[http://en.wikipedia.org/wiki/Haas_F1_Team],[Haas F1 Team],[American]
14,15,15,6.0,0,bottas,77,BOT,http://en.wikipedia.org/wiki/Valtteri_Bottas,Valtteri,Bottas,1989-08-28,Finnish,[alfa],[http://en.wikipedia.org/wiki/Alfa_Romeo_in_Fo...,[Alfa Romeo],[Swiss]
15,16,16,4.0,0,zhou,24,ZHO,http://en.wikipedia.org/wiki/Zhou_Guanyu,Guanyu,Zhou,1999-05-30,Chinese,[alfa],[http://en.wikipedia.org/wiki/Alfa_Romeo_in_Fo...,[Alfa Romeo],[Swiss]
16,17,17,3.0,0,tsunoda,22,TSU,http://en.wikipedia.org/wiki/Yuki_Tsunoda,Yuki,Tsunoda,2000-05-11,Japanese,[alphatauri],[http://en.wikipedia.org/wiki/Scuderia_AlphaTa...,[AlphaTauri],[Italian]
17,18,18,2.0,0,kevin_magnussen,20,MAG,http://en.wikipedia.org/wiki/Kevin_Magnussen,Kevin,Magnussen,1992-10-05,Danish,[haas],[http://en.wikipedia.org/wiki/Haas_F1_Team],[Haas F1 Team],[American]
18,19,19,0.0,0,sargeant,2,SAR,http://en.wikipedia.org/wiki/Logan_Sargeant,Logan,Sargeant,2000-12-31,American,[williams],[http://en.wikipedia.org/wiki/Williams_Grand_P...,[Williams],[British]
19,20,20,0.0,0,lawson,15,LAW,http://en.wikipedia.org/wiki/Liam_Lawson,Liam,Lawson,2002-02-11,New Zealander,[alphatauri],[http://en.wikipedia.org/wiki/Scuderia_AlphaTa...,[AlphaTauri],[Italian]
20,21,21,0.0,0,de_vries,21,DEV,http://en.wikipedia.org/wiki/Nyck_de_Vries,Nyck,de Vries,1995-02-06,Dutch,[alphatauri],[http://en.wikipedia.org/wiki/Scuderia_AlphaTa...,[AlphaTauri],[Italian]
21,22,22,0.0,0,ricciardo,3,RIC,http://en.wikipedia.org/wiki/Daniel_Ricciardo,Daniel,Ricciardo,1989-07-01,Australian,[alphatauri],[http://en.wikipedia.org/wiki/Scuderia_AlphaTa...,[AlphaTauri],[Italian]